import SwiftUI
import SettCore

/// Full reading view for one AI insight — the destination of Home's teaser card.
/// (The Progress tab's Insights feed navigates here too.)
struct InsightDetailView: View {
    let insight: AIInsight

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 12) {
                // Gold audit: insights are ki, not the power level — bone title,
                // cyan sparkles (matches Home's teaser card).
                Label {
                    Text(kindTitle)
                        .foregroundStyle(SettColor.bone)
                } icon: {
                    Image(systemName: "sparkles")
                        .foregroundStyle(SettColor.heroCyan)
                }
                .font(.title3.weight(.semibold))
                Text(dateText)
                    .font(.footnote)
                    .foregroundStyle(SettColor.ash)
                InsightProse(insight.body, bodyFont: .body)
                Text(sourceFootnote)
                    .font(.footnote)
                    .foregroundStyle(SettColor.iron)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .settCard()
            // The screen that IS the AI voice assembles in like the System Voice
            // speaks elsewhere, instead of popping in flat. (materialize collapses
            // to a plain fade under Reduce Motion.)
            .materialize()
            .padding(16)
        }
        .dungeonBackground()
        .navigationTitle("Insight")
        .navigationBarTitleDisplayMode(.inline)
    }

    private var kindTitle: String {
        insight.kind == .weeklyDigest ? "Weekly Digest" : "Workout Note"
    }

    private var dateText: String {
        let start = insight.periodStart.formatted(date: .abbreviated, time: .omitted)
        guard !Calendar.current.isDate(insight.periodStart, inSameDayAs: insight.periodEnd) else {
            return start
        }
        return "\(start) – \(insight.periodEnd.formatted(date: .abbreviated, time: .omitted))"
    }

    private var sourceFootnote: String {
        switch insight.source {
        case .onDevice: "Generated on device"
        case .server: "Generated by AI"
        case .fallbackTemplate: "sett scanner"
        }
    }
}
