import SwiftUI
import SettCore

/// Full reading view for one AI insight — the destination of Home's teaser card.
/// (The Progress tab's Insights feed navigates here too.)
struct InsightDetailView: View {
    let insight: AIInsight

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 12) {
                Label(kindTitle, systemImage: "sparkles")
                    .font(.title3.weight(.semibold))
                    .foregroundStyle(SettColor.saiyanGold)
                Text(dateText)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                Text(bodyText)
                    .font(.body)
                Text(sourceFootnote)
                    .font(.footnote)
                    .foregroundStyle(.tertiary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .settCard()
            .padding(16)
        }
        .background(SettColor.screen)
        .navigationTitle("Insight")
        .navigationBarTitleDisplayMode(.inline)
    }

    private var kindTitle: String {
        insight.kind == .weeklyDigest ? "Weekly Digest" : "Workout Note"
    }

    private var dateText: String {
        let start = insight.periodStart.formatted(date: .abbreviated, time: .omitted)
        guard !Calendar.current.isDate(insight.periodStart, inSameDayAs: insight.periodEnd) else {
            return start
        }
        return "\(start) – \(insight.periodEnd.formatted(date: .abbreviated, time: .omitted))"
    }

    /// Insight bodies are markdown; fall back to plain text if parsing fails.
    private var bodyText: AttributedString {
        (try? AttributedString(
            markdown: insight.body,
            options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
        )) ?? AttributedString(insight.body)
    }

    private var sourceFootnote: String {
        switch insight.source {
        case .onDevice: "Generated on device"
        case .server: "Generated by AI"
        case .fallbackTemplate: "sett scanner"
        }
    }
}
