import SwiftUI
import SettCore

/// Card 6 — the AI insights feed: weekly digests as expandable rows with a gold
/// left-border accent and markdown-ish bodies, post-workout notes as compact
/// rows, "Generated by AI" caption at the foot.
struct InsightsCard: View {
    let insights: [AIInsight]

    @State private var expandedIDs: Set<UUID> = []

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Insights", systemImage: "sparkles")
                .font(.headline)
            if insights.isEmpty {
                Text("First weekly insight arrives after your first full week.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            } else {
                VStack(spacing: 8) {
                    ForEach(insights.prefix(10)) { insight in
                        if insight.kind == .weeklyDigest {
                            digestRow(insight)
                        } else {
                            compactRow(insight)
                        }
                    }
                }
                Text("Generated by AI")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .settCard()
    }

    // MARK: Weekly digest (expandable, gold left border)

    private func digestRow(_ insight: AIInsight) -> some View {
        let isExpanded = expandedIDs.contains(insight.id)
        return Button {
            withAnimation(.snappy) {
                if isExpanded {
                    expandedIDs.remove(insight.id)
                } else {
                    expandedIDs.insert(insight.id)
                }
            }
        } label: {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Text("Weekly Digest")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(.primary)
                    Spacer()
                    Text(insight.periodEnd.formatted(date: .abbreviated, time: .omitted))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Image(systemName: "chevron.down")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(.tertiary)
                        .rotationEffect(.degrees(isExpanded ? 180 : 0))
                }
                if isExpanded {
                    InsightProse(insight.body)
                        .frame(maxWidth: .infinity, alignment: .leading)
                } else {
                    Text(firstLine(of: insight.body))
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.leading)
                        .lineLimit(2)
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
            .padding(12)
            .padding(.leading, 8)
            .background(SettColor.cardNested, in: RoundedRectangle(cornerRadius: 8, style: .continuous))
            .overlay(alignment: .leading) {
                Capsule()
                    .fill(SettColor.heroCyan)
                    .frame(width: 3)
                    .padding(.vertical, 10)
                    .padding(.leading, 6)
            }
        }
        .buttonStyle(.plain)
        .accessibilityHint(isExpanded ? "Collapses the digest" : "Expands the digest")
    }

    // MARK: Post-workout (compact)

    private func compactRow(_ insight: AIInsight) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 8) {
            Image(systemName: "bolt.fill")
                .font(.caption)
                .foregroundStyle(SettColor.heroCyan)
                .accessibilityHidden(true)
            Text(firstLine(of: insight.body))
                .font(.footnote)
                .lineLimit(2)
                .frame(maxWidth: .infinity, alignment: .leading)
            Text(insight.createdAt.formatted(date: .numeric, time: .omitted))
                .font(.caption2)
                .foregroundStyle(.tertiary)
        }
        .padding(.vertical, 4)
    }

    private func firstLine(of text: String) -> String {
        text.split(whereSeparator: \.isNewline).first.map(String.init) ?? text
    }
}

// MARK: - Insight prose (lightweight markdown → styled blocks)

/// Renders an AI insight's markdown as real blocks: `## X` becomes a cyan section
/// header, blank lines separate paragraphs, `- ` becomes a bullet, and inline
/// **bold**/*italic* still resolve per line. Plain `Text(LocalizedStringKey:)` left the
/// literal "##" showing; `AttributedString(markdown:)` dropped the headers entirely.
struct InsightProse: View {
    let markdown: String
    var bodyFont: Font

    init(_ markdown: String, bodyFont: Font = .subheadline) {
        self.markdown = markdown
        self.bodyFont = bodyFont
    }

    private enum Block { case heading(String), bullet(String), paragraph(String) }

    private var blocks: [Block] {
        markdown.split(separator: "\n", omittingEmptySubsequences: true).compactMap { raw in
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.isEmpty { return nil }
            if line.hasPrefix("## ") { return .heading(String(line.dropFirst(3))) }
            if line.hasPrefix("# ") { return .heading(String(line.dropFirst(2))) }
            if line.hasPrefix("- ") || line.hasPrefix("* ") { return .bullet(String(line.dropFirst(2))) }
            return .paragraph(line)
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            ForEach(Array(blocks.enumerated()), id: \.offset) { _, block in
                switch block {
                case .heading(let text):
                    Text(text)
                        .font(.subheadline.weight(.bold))
                        .foregroundStyle(SettColor.heroCyan)
                        .padding(.top, 2)
                case .bullet(let text):
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Text("•").foregroundStyle(SettColor.heroCyan)
                        Text(LocalizedStringKey(text)).foregroundStyle(SettColor.bone)
                    }
                    .font(bodyFont)
                    .fixedSize(horizontal: false, vertical: true)
                case .paragraph(let text):
                    Text(LocalizedStringKey(text))
                        .font(bodyFont)
                        .foregroundStyle(SettColor.bone)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}
